CREATE TABLE Clinica (
[Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[Email] VARCHAR (50) UNIQUE NOT NULL,
[Senha] VARCHAR (20) NOT NULL,
[Cnpj] VARCHAR(18) UNIQUE NOT NULL,
[StatusAtividade] BIT NOT NULL,
[TelefoneCom] VARCHAR (13) NOT NULL,
[Nome] VARCHAR(50) NOT NULL,
[Estado] VARCHAR(2) NOT NULL,
[Cidade] VARCHAR (50) NOT NULL,
[Bairro] VARCHAR(50) NOT NULL,
[Logradouro] VARCHAR(50) NOT NULL,
[Numero] INTEGER NOT NULL,
[Complemento] VARCHAR(50)
)