CREATE TABLE Endereco (
[Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[Bairro] VARCHAR(50) NOT NULL,
[Rua] VARCHAR(50) NOT NULL,
[IdClinica] INTEGER NOT NULL,
CONSTRAINT [FK_Endereco_Clinica] FOREIGN KEY(IdClinica) REFERENCES [Clinica] ([Id])
)